
import { Link } from 'react-router-dom';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import LikeButton from '@/components/social/LikeButton';
import EnhancedShareButton from '@/components/social/EnhancedShareButton';
import { formatDistanceToNow } from 'date-fns';
import { useState } from 'react';
import { Skeleton } from '@/components/ui/skeleton';
import { Bot, ExternalLink } from 'lucide-react';

interface FailCardSocialProps {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  username: string;
  date: string;
  likes: number;
  category: string;
  tags: string[];
  aiModel: string;
  featured: boolean;
  sourceUrl?: string;
  sourcePlatform?: string;
  autoGenerated?: boolean;
}

const FailCardSocial = (props: FailCardSocialProps) => {
  const { 
    id, title, description, imageUrl, username, date, likes, category, 
    tags, aiModel, sourceUrl, sourcePlatform, autoGenerated 
  } = props;
  const [imageLoading, setImageLoading] = useState(true);
  const [imageError, setImageError] = useState(false);
  
  const handleImageLoad = () => {
    setImageLoading(false);
  };
  
  const handleImageError = () => {
    setImageLoading(false);
    setImageError(true);
  };
  
  const isAutoDiscovered = autoGenerated || tags?.includes('auto-discovered');
  
  return (
    <Card className="overflow-hidden transition-all hover:shadow-md">
      <Link to={`/fail/${id}`} className="block">
        <div className="aspect-[4/3] overflow-hidden relative">
          {imageLoading && (
            <Skeleton className="w-full h-full absolute inset-0" />
          )}
          {!imageError ? (
            <img 
              src={imageUrl} 
              alt={title} 
              className={`w-full h-full object-cover transition-transform hover:scale-105 ${
                imageLoading ? 'opacity-0' : 'opacity-100'
              }`}
              onLoad={handleImageLoad}
              onError={handleImageError}
              loading="lazy"
            />
          ) : (
            <div className="w-full h-full bg-muted flex items-center justify-center">
              <span className="text-muted-foreground text-sm">Image not available</span>
            </div>
          )}
          
          <div className="absolute top-2 left-2 flex gap-2">
            {category && (
              <Badge className="bg-primary/80 hover:bg-primary/80">
                {category}
              </Badge>
            )}
            {isAutoDiscovered && (
              <Badge variant="secondary" className="flex items-center">
                <Bot className="w-3 h-3 mr-1" />
                Auto
              </Badge>
            )}
          </div>
          
          {sourceUrl && (
            <div className="absolute top-2 right-2">
              <a
                href={sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                onClick={(e) => e.stopPropagation()}
                className="bg-black/70 text-white p-1 rounded-full hover:bg-black/80 transition-colors"
                title="View original source"
              >
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          )}
        </div>
        
        <CardContent className="p-4">
          <h3 className="font-bold text-lg line-clamp-2 mb-2" title={title}>
            {title}
          </h3>
          
          <div className="flex items-center gap-2 mb-2">
            {aiModel && (
              <Badge variant="outline">
                {aiModel}
              </Badge>
            )}
            {sourcePlatform && (
              <Badge variant="secondary">
                {sourcePlatform}
              </Badge>
            )}
          </div>
          
          {tags && tags.length > 0 && (
            <div className="flex flex-wrap gap-1 mt-2">
              {tags.slice(0, 3).map((tag, index) => (
                <Badge key={index} variant="secondary" className="text-xs">
                  {tag}
                </Badge>
              ))}
              {tags.length > 3 && (
                <span className="text-xs text-muted-foreground">+{tags.length - 3} more</span>
              )}
            </div>
          )}
        </CardContent>
      </Link>
      
      <CardFooter className="p-4 pt-0 flex items-center justify-between">
        <div className="flex items-center">
          <Avatar className="h-6 w-6 mr-2">
            <AvatarFallback>
              {isAutoDiscovered ? <Bot className="w-3 h-3" /> : username.charAt(0).toUpperCase()}
            </AvatarFallback>
            <AvatarImage src={`https://avatar.vercel.sh/${username}`} />
          </Avatar>
          <div className="text-xs text-muted-foreground">
            <span className="font-medium">
              {isAutoDiscovered ? 'AI Discovery' : username}
            </span>
            <span className="ml-2">
              {formatDistanceToNow(new Date(date), { addSuffix: true })}
            </span>
          </div>
        </div>
        
        <div className="flex items-center space-x-1">
          <LikeButton failId={id} initialLikes={likes} />
          <EnhancedShareButton 
            failId={id} 
            title={title} 
            imageUrl={imageUrl}
            category={category}
            description={description}
          />
        </div>
      </CardFooter>
    </Card>
  );
};

export default FailCardSocial;
